### ISSUE TITLE
Not working

### ISSUE THREAD

**Issue by arupgsh** [pawneetdev/scraper#1]
The scripts are not working now.

**Comment by pawneetdev** [comment]
Amazon has changed the front end code base. Since, I used pattern matching to scrap the data, its not working. I will try to update it soon.

**Comment by pawneetdev** [comment]
The code has been fixed. Thanx for reporting.

**Comment by arupgsh** [comment]
Amazon is working but Flipkart crawler is not scrapping data.

**Comment by pawneetdev** [comment]
Its working absolutely fine for me. Try opening flipkart site. And check that u r able to access it or not. Maybe there's some dns issue in your network if u r not able to open flipkart.com.

**Comment by arupgsh** [comment]
Ok, thanks for the help.
